/**
 * 一段极短且无声的 MP3 Base64 数据。
 * 用于在 iOS Safari (WebKit) 中，保持网页后台 Audio Playing Exemption 的状态锁。
 * 在网页转入后台或屏幕熄灭时，如果音频结束（触发 onend），WebKit 会剥夺 JavaScript 和网络权限。
 * 在等待下一首音频由于网络延迟解析并加载的期间，循环播放此静音音频防止冻结。
 */
export const SILENT_AUDIO_BASE64 =
  'data:audio/mpeg;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU5LjI3LjEwMAAAAAAAAAAAAAAA//twwAACqAAAIMAAADEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQn/+3DAAAJSAAAAwwAAAMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQk'
