import { Vec2, Vec3 } from 'gl-matrix';
import { BaseRenderer } from '../base.ts';
declare class ControlPoint {
    color: Vec3;
    location: Vec2;
    uTangent: Vec2;
    vTangent: Vec2;
    private _uRot;
    private _vRot;
    private _uScale;
    private _vScale;
    constructor();
    get uRot(): number;
    get vRot(): number;
    set uRot(value: number);
    set vRot(value: number);
    get uScale(): number;
    get vScale(): number;
    set uScale(value: number);
    set vScale(value: number);
    private updateUTangent;
    private updateVTangent;
}
export declare class MeshGradientRenderer extends BaseRenderer {
    private gl;
    private lastFrameTime;
    private frameTime;
    private currentImageData?;
    private lastTickTime;
    private smoothedVolume;
    private volume;
    private tickHandle;
    private maxFPS;
    private paused;
    private staticMode;
    private mainProgram;
    private manualControl;
    private reduceImageSizeCanvas;
    private targetSize;
    private currentSize;
    private isNoCover;
    private meshStates;
    private _disposed;
    private frameCount;
    private lastFPSUpdate;
    private currentFPS;
    private enablePerformanceMonitoring;
    setManualControl(enable: boolean): void;
    setWireFrame(enable: boolean): void;
    getControlPoint(x: number, y: number): ControlPoint | undefined;
    resizeControlPoints(width: number, height: number): void;
    resetSubdivition(subDivisions: number): void;
    private onTick;
    private checkIfResize;
    private onRedraw;
    private onTickBinded;
    private requestTick;
    private supportTextureFloat;
    constructor(canvas: HTMLCanvasElement);
    protected onResize(width: number, height: number): void;
    setStaticMode(enable: boolean): void;
    setFPS(fps: number): void;
    pause(): void;
    resume(): void;
    setAlbum(albumSource?: string | HTMLImageElement | HTMLVideoElement, isVideo?: boolean): Promise<void>;
    setLowFreqVolume(volume: number): void;
    setHasLyric(_hasLyric: boolean): void;
    dispose(): void;
    enablePerformanceMonitor(enable: boolean): void;
    getCurrentFPS(): number;
    private updatePerformanceStats;
}
export {};
//# sourceMappingURL=index.d.ts.map